[build-system]
requires = ["setuptools>=42.0.0", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"


[tool.setuptools_scm]
write_to = "src/napari_metadata/_version.py"

[tool.ruff]
line-length = 88
target-version = "py38"
src = ["src"]
